-- =============================================================================
-- マスターデータ初期投入
-- 実行前に schema.sql でテーブル構造を作成済みであること
-- =============================================================================

-- -----------------------------------------------------------------------------
-- system_accounts (初期管理者アカウント password: password)
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `system_accounts` (`name`, `email`, `password`, `role`, `is_active`, `email_verified_at`, `created_at`, `updated_at`) VALUES
('管理者アカウント1', 'admin@misechoku.jp', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', 1, NULL, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- industries
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `industries` (`id`, `name`, `del_flg`, `created_at`, `updated_at`) VALUES
(1, 'キャバクラ', 0, NOW(), NOW()),
(2, 'クラブ', 0, NOW(), NOW()),
(3, 'ラウンジ', 0, NOW(), NOW()),
(4, 'ガールズバー', 0, NOW(), NOW()),
(5, 'コンカフェ', 0, NOW(), NOW()),
(6, 'スナック', 0, NOW(), NOW()),
(9, 'その他', 0, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- cast_tags
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `cast_tags` (`id`, `category`, `name`, `del_flg`, `sort_order`, `created_at`, `updated_at`) VALUES
(1, 'looks', 'スレンダー', 0, 1, NOW(), NOW()),
(2, 'looks', '普通', 0, 2, NOW(), NOW()),
(3, 'looks', 'グラマー', 0, 3, NOW(), NOW()),
(4, 'looks', 'ぽっちゃり', 0, 4, NOW(), NOW()),
(5, 'looks', '高長身', 0, 5, NOW(), NOW()),
(6, 'looks', '小柄', 0, 6, NOW(), NOW()),
(7, 'looks', 'スタイル抜群', 0, 7, NOW(), NOW()),
(8, 'looks', 'キレイ系', 0, 8, NOW(), NOW()),
(9, 'looks', '可愛い系', 0, 9, NOW(), NOW()),
(10, 'looks', 'セクシー系', 0, 10, NOW(), NOW()),
(11, 'looks', '巨乳', 0, 11, NOW(), NOW()),
(12, 'looks', 'ギャル', 0, 12, NOW(), NOW()),
(13, 'looks', '清楚系', 0, 13, NOW(), NOW()),
(14, 'looks', 'お姉さん系', 0, 14, NOW(), NOW()),
(15, 'looks', '癒し系', 0, 15, NOW(), NOW()),
(16, 'looks', '萌え系', 0, 16, NOW(), NOW()),
(17, 'personality', 'モデル経験あり', 0, 17, NOW(), NOW()),
(18, 'personality', 'ハーフ', 0, 18, NOW(), NOW()),
(19, 'personality', 'アイドル経験有り', 0, 19, NOW(), NOW()),
(20, 'personality', 'インフルエンサー', 0, 20, NOW(), NOW()),
(21, 'personality', '芸能人', 0, 21, NOW(), NOW()),
(22, 'personality', 'OL/一般職', 0, 22, NOW(), NOW()),
(23, 'personality', '学生', 0, 23, NOW(), NOW()),
(24, 'personality', '顔出しOK', 0, 24, NOW(), NOW()),
(26, 'looks', '初心者/未経験', 0, 26, NOW(), NOW()),
(32, 'personality', '社交的', 0, 1, NOW(), NOW()),
(33, 'personality', '明るい', 0, 2, NOW(), NOW()),
(34, 'personality', 'おしゃべり上手', 0, 3, NOW(), NOW()),
(35, 'personality', 'わいわい系', 0, 4, NOW(), NOW()),
(36, 'personality', 'パリピ系', 0, 5, NOW(), NOW()),
(37, 'personality', 'おとなしめ', 0, 6, NOW(), NOW()),
(38, 'personality', 'おっとり', 0, 7, NOW(), NOW()),
(39, 'personality', 'しっとり', 0, 8, NOW(), NOW()),
(40, 'personality', '接客上手', 0, 9, NOW(), NOW()),
(41, 'personality', 'お酒飲める人', 0, 10, NOW(), NOW()),
(42, 'personality', 'お酒苦手', 0, 11, NOW(), NOW()),
(43, 'personality', '姉御肌', 0, 12, NOW(), NOW()),
(44, 'personality', '妹気質', 0, 13, NOW(), NOW()),
(45, 'personality', '連絡マメ', 0, 14, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- shop_tags
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `shop_tags` (`id`, `category`, `target`, `name`, `del_flg`, `sort_order`, `created_at`, `updated_at`) VALUES
(1, 'work_style', 'job', '1ヶ月払い', 0, 1, NOW(), NOW()),
(2, 'work_style', 'job', '15日払い', 0, 2, NOW(), NOW()),
(3, 'work_style', 'job', '10日払い', 0, 3, NOW(), NOW()),
(4, 'work_style', 'job', '1週間払い', 0, 4, NOW(), NOW()),
(5, 'work_style', 'job', '翌日払い', 0, 5, NOW(), NOW()),
(6, 'work_style', 'job', '全額日払い', 0, 6, NOW(), NOW()),
(7, 'work_style', 'job', '日払い可', 0, 7, NOW(), NOW()),
(8, 'work_style', 'job', '交通費支給', 0, 8, NOW(), NOW()),
(9, 'work_style', 'job', '高額時給', 0, 9, NOW(), NOW()),
(10, 'work_style', 'job', '高額バック支給', 0, 10, NOW(), NOW()),
(11, 'work_style', 'job', '入店祝い金支給', 0, 11, NOW(), NOW()),
(12, 'work_style', 'job', '給料手渡し', 0, 12, NOW(), NOW()),
(13, 'work_style', 'job', '給料UP', 0, 13, NOW(), NOW()),
(14, 'work_style', 'job', '売上バック有り', 0, 14, NOW(), NOW()),
(15, 'work_style', 'job', '同伴バック有り', 0, 15, NOW(), NOW()),
(16, 'work_style', 'job', 'シャンパンバック有り', 0, 16, NOW(), NOW()),
(17, 'work_style', 'job', 'その他バック有り', 0, 17, NOW(), NOW()),
(18, 'work_style', 'job', 'ドリンクバック', 0, 18, NOW(), NOW()),
(19, 'work_style', 'job', '指名バック', 0, 19, NOW(), NOW()),
(32, 'work_style', 'job', '週1からOK', 0, 1, NOW(), NOW()),
(33, 'work_style', 'job', '短期OK', 0, 2, NOW(), NOW()),
(34, 'work_style', 'job', '1日1h以内', 0, 3, NOW(), NOW()),
(35, 'work_style', 'job', '1日2h以内', 0, 4, NOW(), NOW()),
(36, 'work_style', 'job', '1日3h以内', 0, 5, NOW(), NOW()),
(37, 'work_style', 'job', '1日4h以内', 0, 6, NOW(), NOW()),
(38, 'work_style', 'job', '未経験者歓迎', 0, 7, NOW(), NOW()),
(39, 'work_style', 'job', '出稼ぎOK', 0, 8, NOW(), NOW()),
(40, 'work_style', 'job', '終電上がりOK', 0, 9, NOW(), NOW()),
(41, 'work_style', 'job', 'WワークOK', 0, 10, NOW(), NOW()),
(47, 'work_style', 'job', '登録制有り', 0, 3, NOW(), NOW()),
(48, 'work_style', 'job', '何回か体入OK', 0, 4, NOW(), NOW()),
(49, 'work_style', 'job', '早上げ無し', 0, 12, NOW(), NOW()),
(50, 'work_style', 'job', '早上がり有り', 0, 13, NOW(), NOW()),
(54, 'atmosphere', 'shop', 'わいわい', 0, 1, NOW(), NOW()),
(55, 'atmosphere', 'shop', 'しっとり', 0, 2, NOW(), NOW()),
(56, 'atmosphere', 'shop', 'おっとり', 0, 3, NOW(), NOW()),
(57, 'atmosphere', 'shop', 'アットホーム', 0, 4, NOW(), NOW()),
(58, 'atmosphere', 'shop', '大型店', 0, 5, NOW(), NOW()),
(59, 'atmosphere', 'shop', '中型店', 0, 6, NOW(), NOW()),
(60, 'atmosphere', 'shop', '小さいお店', 0, 7, NOW(), NOW()),
(61, 'atmosphere', 'shop', '高級店', 0, 8, NOW(), NOW()),
(62, 'atmosphere', 'shop', '大衆店', 0, 9, NOW(), NOW()),
(63, 'atmosphere', 'shop', 'キャスト多数', 0, 10, NOW(), NOW()),
(64, 'atmosphere', 'shop', '少人数', 0, 11, NOW(), NOW()),
(65, 'atmosphere', 'shop', '上下関係無し', 0, 12, NOW(), NOW()),
(66, 'atmosphere', 'shop', '派閥無し', 0, 13, NOW(), NOW()),
(67, 'atmosphere', 'shop', '新規オープン', 0, 14, NOW(), NOW()),
(68, 'atmosphere', 'shop', 'リニューアルオープン', 0, 15, NOW(), NOW()),
(69, 'atmosphere', 'shop', 'ステージ有り', 0, 16, NOW(), NOW()),
(70, 'atmosphere', 'shop', 'カウンターのみ', 0, 17, NOW(), NOW()),
(71, 'atmosphere', 'shop', 'カラオケ有り', 0, 18, NOW(), NOW()),
(72, 'atmosphere', 'shop', 'カラオケ無し', 0, 19, NOW(), NOW()),
(73, 'atmosphere', 'shop', 'VIPルール完備', 0, 20, NOW(), NOW()),
(86, 'atmosphere', 'shop', '日曜営業', 0, 3, NOW(), NOW()),
(87, 'atmosphere', 'shop', '定休日無し', 0, 4, NOW(), NOW()),
(89, 'facility', 'shop', '駐車場有り', 0, 1, NOW(), NOW()),
(90, 'facility', 'shop', '車通勤OK', 0, 2, NOW(), NOW()),
(91, 'facility', 'shop', '寮有り', 0, 3, NOW(), NOW()),
(92, 'facility', 'shop', '即日入居可寮有り', 0, 4, NOW(), NOW()),
(93, 'facility', 'shop', '託児所有り', 0, 5, NOW(), NOW()),
(94, 'facility', 'shop', '個人ロッカー有り', 0, 6, NOW(), NOW()),
(95, 'facility', 'shop', 'キャスト専用トイレ有り', 0, 7, NOW(), NOW()),
(96, 'facility', 'shop', 'ステージ有り', 0, 3, NOW(), NOW()),
(97, 'facility', 'shop', 'カウンターのみ', 0, 4, NOW(), NOW()),
(98, 'facility', 'shop', 'カラオケ有り', 0, 5, NOW(), NOW()),
(99, 'facility', 'shop', 'カラオケ無し', 0, 6, NOW(), NOW()),
(100, 'facility', 'shop', 'VIPルール完備', 0, 7, NOW(), NOW()),
(101, 'facility', 'shop', '禁煙店', 0, 8, NOW(), NOW()),
(102, 'facility', 'shop', 'コロナ対策実施', 0, 9, NOW(), NOW()),
(103, 'facility', 'shop', '送り有り', 0, 1, NOW(), NOW()),
(104, 'facility', 'shop', '迎え有り', 0, 2, NOW(), NOW()),
(105, 'facility', 'shop', '駅からスグ', 0, 5, NOW(), NOW()),
(106, 'facility', 'shop', '駅徒歩5分', 0, 6, NOW(), NOW()),
(107, 'facility', 'shop', '駅徒歩10分', 0, 7, NOW(), NOW()),
(115, 'welcome', 'job', '未経験', 0, 1, NOW(), NOW()),
(116, 'welcome', 'job', 'シングルマザーOK', 0, 2, NOW(), NOW()),
(117, 'welcome', 'job', '経験者優遇', 0, 3, NOW(), NOW()),
(118, 'welcome', 'job', '学生歓迎', 0, 4, NOW(), NOW()),
(119, 'welcome', 'job', '主婦歓迎', 0, 5, NOW(), NOW()),
(120, 'welcome', 'job', 'ブランク歓迎', 0, 6, NOW(), NOW()),
(121, 'welcome', 'job', 'お酒NG歓迎', 0, 7, NOW(), NOW()),
(122, 'welcome', 'job', 'ニューオープン', 0, 8, NOW(), NOW()),
(123, 'welcome', 'job', '登録制有り', 0, 9, NOW(), NOW()),
(124, 'welcome', 'job', '日曜営業', 0, 10, NOW(), NOW()),
(125, 'welcome', 'job', '10代歓迎', 0, 11, NOW(), NOW()),
(126, 'welcome', 'job', '30代歓迎', 0, 12, NOW(), NOW()),
(127, 'welcome', 'job', '40代歓迎', 0, 13, NOW(), NOW()),
(128, 'welcome', 'job', '50代歓迎', 0, 14, NOW(), NOW()),
(129, 'welcome', 'job', 'コロナ対策実施', 0, 15, NOW(), NOW()),
(130, 'welcome', 'job', 'タトゥーOK', 0, 16, NOW(), NOW()),
(131, 'welcome', 'job', '禁煙店', 0, 17, NOW(), NOW()),
(132, 'welcome', 'job', '定休日無し', 0, 18, NOW(), NOW()),
(133, 'welcome', 'job', 'ぽっちゃりOK', 0, 19, NOW(), NOW()),
(134, 'welcome', 'job', '何回か体入OK', 0, 20, NOW(), NOW()),
(146, 'welcome', 'job', '未経験者歓迎', 0, 1, NOW(), NOW()),
(149, 'benefit', 'job', 'レンタル衣装有り', 0, 1, NOW(), NOW()),
(150, 'benefit', 'job', '服装自由', 0, 2, NOW(), NOW()),
(151, 'benefit', 'job', 'ヘアメイク有り', 0, 3, NOW(), NOW()),
(152, 'benefit', 'job', 'ヘアメイク無料', 0, 4, NOW(), NOW()),
(153, 'benefit', 'job', 'ヘアメイク不要', 0, 5, NOW(), NOW()),
(154, 'benefit', 'job', '髪型自由', 0, 6, NOW(), NOW()),
(155, 'benefit', 'job', '小物レンタル無料', 0, 7, NOW(), NOW()),
(156, 'benefit', 'job', 'レンタルドレス', 0, 8, NOW(), NOW()),
(157, 'benefit', 'job', 'レンタル衣装無料', 0, 9, NOW(), NOW()),
(158, 'benefit', 'job', '手ぶらで体入OK', 0, 10, NOW(), NOW()),
(159, 'benefit', 'job', '送り有り', 0, 11, NOW(), NOW()),
(160, 'benefit', 'job', '迎え有り', 0, 12, NOW(), NOW()),
(161, 'benefit', 'job', '駅からスグ', 0, 13, NOW(), NOW()),
(162, 'benefit', 'job', '早上げ無し', 0, 14, NOW(), NOW()),
(163, 'benefit', 'job', 'ノルマ無し', 0, 15, NOW(), NOW()),
(164, 'benefit', 'job', '福利厚生・提携先割引有り', 0, 16, NOW(), NOW()),
(165, 'benefit', 'job', '早上がり有り', 0, 17, NOW(), NOW()),
(166, 'benefit', 'job', 'ドリンクバック', 0, 18, NOW(), NOW()),
(167, 'benefit', 'job', '指名バック', 0, 19, NOW(), NOW()),
(168, 'benefit', 'job', 'ヘアメイク提携割引有り', 0, 20, NOW(), NOW()),
(169, 'benefit', 'job', '託児用提携割引有り', 0, 21, NOW(), NOW()),
(170, 'benefit', 'job', '衣装割引き有り', 0, 22, NOW(), NOW()),
(171, 'benefit', 'job', '駅徒歩5分', 0, 23, NOW(), NOW()),
(172, 'benefit', 'job', '駅徒歩10分', 0, 24, NOW(), NOW()),
(173, 'benefit', 'job', '売上バック有り', 0, 25, NOW(), NOW()),
(174, 'benefit', 'job', '同伴バック有り', 0, 26, NOW(), NOW()),
(175, 'benefit', 'job', 'シャンパンバック有り', 0, 27, NOW(), NOW()),
(176, 'benefit', 'job', 'その他バック有り', 0, 28, NOW(), NOW()),
(180, 'benefit', 'job', '寮有り', 0, 11, NOW(), NOW()),
(181, 'benefit', 'job', '即日入居可寮有り', 0, 12, NOW(), NOW()),
(182, 'benefit', 'job', '託児所有り', 0, 13, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- ng_words
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `ng_words` (`id`, `word`, `is_active`, `created_at`, `updated_at`) VALUES
(1,  '個人連絡先', 1, NOW(), NOW()),
(2,  '連絡先交換', 1, NOW(), NOW()),
(3,  'LINE交換',   1, NOW(), NOW()),
(4,  'ライン交換', 1, NOW(), NOW()),
(5,  'Instagram',  1, NOW(), NOW()),
(6,  'インスタ',   1, NOW(), NOW()),
(7,  'X交換',      1, NOW(), NOW()),
(8,  'Twitter交換',1, NOW(), NOW()),
(9,  'カカオ',     1, NOW(), NOW()),
(10, 'Kakao',      1, NOW(), NOW()),
(11, 'Telegram',   1, NOW(), NOW()),
(12, 'テレグラム', 1, NOW(), NOW()),
(13, '直引き',     1, NOW(), NOW()),
(14, '店外',       1, NOW(), NOW()),
(15, '裏オプ',     1, NOW(), NOW()),
(16, '本番',       1, NOW(), NOW()),
(17, 'ホ別',       1, NOW(), NOW()),
(18, '会うだけ',   1, NOW(), NOW()),
(19, '条件あり',   1, NOW(), NOW()),
(20, '個別契約',   1, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- review_contents
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `review_contents` (`id`, `content`, `del_flg`, `created_at`, `updated_at`) VALUES
(1,  '店内は清潔に保たれていますか？',         0, NOW(), NOW()),
(2,  'スタッフの対応は親切ですか？',           0, NOW(), NOW()),
(3,  '店内の雰囲気はリラックスできますか？',   0, NOW(), NOW()),
(4,  '給料や待遇に満足していますか？',         0, NOW(), NOW()),
(5,  'シフトの調整や融通が効きますか？',       0, NOW(), NOW()),
(6,  '来店するお客様の質に満足していますか？', 0, NOW(), NOW()),
(7,  '店舗内での安全性は確保されていますか？', 0, NOW(), NOW()),
(8,  '教育やサポート体制は十分ですか？',       0, NOW(), NOW()),
(9,  '店舗での働きやすさに満足していますか？', 0, NOW(), NOW()),
(10, '店舗の立地条件は良いですか？',           0, NOW(), NOW());

-- -----------------------------------------------------------------------------
-- column_categories
-- -----------------------------------------------------------------------------
INSERT IGNORE INTO `column_categories` (`id`, `name`, `directory`, `del_flg`, `created_at`, `updated_at`) VALUES
(1, 'キャバクラ情報', 'cabaret-info', 0, NOW(), NOW()),
(2, 'ラウンジ情報',   'lounge-info',  0, NOW(), NOW()),
(4, '面接対策',       'interview',    0, NOW(), NOW());
